// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	Name          string
	Url           string
	UserID        string
	LastFetchedAt sql.NullTime
}

type Follow struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	FeedID    string
	UserID    string
}

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Name      string
	ApiKey    string
}
