// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Name      string
	ApiKey    string
}
